spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.43.146/alaputsell?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    port: 6379
#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
#  level:
#    com.imooc.LoggerTest: debug

wechat:
  #公众账号，用于授权
  mpAppId: wx55e2ec47a66cb11e
  mpAppSecret: 452f940240ca3ad726dacc8bdb8c8906

  #开放平台，用于卖家扫码登陆
  openAppId: wx55e2ec47a66cb11e
  openAppSecret: 452f940240ca3ad726dacc8bdb8c8906

  #支付/商户号
  mchId: 11
  mchKey: 11
  #发起支付不需要证书，退款需要
  keyPath:
  notifyUrl: http://alapot.nat300.top/sell/pay/notify
  templateId:
    orderSatus: qUROCT8gLMkMpeclL5qxDB6F8zNd3-UeP6oSTOABVbY

projecturl:
  wechatMpAuthorize: http://alapot.nat300.top
  wechatOpenAuthorize: http://alapot.nat300.top
  sell: http://alapot.nat300.top
logging:
  level:
    com.imooc.dataobject.mapper: trace
mybatis:
  mapper-locations: classpath:mapper/*.xml

# 又拍云服务 见 https://console.upyun.com/services/file/
upyun:
  bucketName: XXX
  userName: xxx
  password: xxxx
  imageHost: http://xxx.com/
server:
  servlet:
    context-path: /sell
    